Add class addBook - Week 1 - Module 2
fabianofrank/awesome-books pull request #3
Opened 2021-11-23 21:22 UTC by fabianofrank

Replace all objects for classes

2021-11-23 22:06 UTC, rukundoeric requested changes
Hi @fabianofrank, 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 

## Required Changes ♻️
  - [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
  - [x] Check the comments under the review.

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-11-23 22:06 UTC, rukundoeric commented on script.js
> +class AddBook {
- [ ] <b>REQUIRED:</b> `AddBook` should not be a class. it should be a function.

2021-11-23 22:06 UTC, rukundoeric commented on script.js
>  function removeBook() {
- [ ] <b>REQUIRED:</b> And all functions should be inside `Book` class. Kindly do that to comply with the project requirements. here is an example:
```js
class Books {
  constructor() {
    this.books = [];
  }

  addBook(title, author) {
  }

  removeBook(bookID) {
  }

  // getter method
  getBooks() {
  }
}

```

2021-11-24 16:45 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

**Hi team**,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-24 19:03 UTC, merged